### ISSUE TITLE
Dialog is not scrollable

### ISSUE THREAD

**Issue by RachelTakeuchi-minted** [cloudflare/react-modal2#11]
How can I make this dialog scrollable if there is a lot of text?

**Comment by thejameskyle** [comment]
This module doesn't include any kind of styles. Thats up to you to provide.

You can see how my team built it here: https://github.com/cloudflare/cf-component-modal

More specifically:
- https://github.com/cloudflare/cf-component-modal/blob/master/src/Modal.js#L38
- https://github.com/cloudflare/cf-component-modal/blob/master/example/style.css#L29-L33

**Comment by jonathan-stone** [comment]
Links are dead. Is that example still around somewhere?

**Comment by thejameskyle** [comment]
same files within here https://github.com/cloudflare/cf-ui/tree/master/packages/cf-component-modal
