### ISSUE TITLE
Warning Use prop-type package 

### ISSUE THREAD

**Issue by devdlabs** [cloudflare/react-modal2#23]
I updated to new version but still getting it -

> `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm`

**Comment by flof** [comment]
I have the same problem. It seems that version 4.0.0 in npm doesn't containt the switch to the prop-types package.

**Comment by sejoker** [comment]
@flof @devdlabs checkout out version 3.2, it contains migration to `prop-types` package.
