### ISSUE TITLE
What is 4.0.0

### ISSUE THREAD

**Issue by klimashkin** [cloudflare/react-modal2#25]
Seems like 3.2.0 is newer than 4.0.0 and contains more fixes according to commits history?

**Comment by klimashkin** [comment]
@tajo @thejameskyle what version community should use? : )

**Comment by jwineman** [comment]
We have no idea who published 4.0.0 lol.  I would recommend 3.2.0  I haven't diffed them yet to see whats changed.

**Comment by klimashkin** [comment]
@thejameskyle published : )
https://github.com/cloudflare/react-modal2/commit/2811d5a1e7dc96d5457cdea11c4daa4a58c6c681

**Comment by scniro** [comment]
@jwineman looking like 4.0 has hulksmashed my app hard. Reverting. Yea unsure what's going on here but I'm glad I found this

**Comment by sejoker** [comment]
@jwineman @tajo I suggest deprecating 4.0.0 in favor of latest 3.x version.

**Comment by jwineman** [comment]
Agreed @sejoker - I deprecated 4.0.0.
