### ISSUE TITLE
Refs in index.js seems to create trouble in 2.0.0

### ISSUE THREAD

**Issue by paazmaya** [cloudflare/react-modal2#5]
After migrating from `1.0.3` to `2.0.0`, started to receive the following error:

```
Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. 
You might be adding a ref to a component that was not created inside a component's `render` method, 
or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

And it was still persistent even after cleaning my component from using `ref` altogether.

Once commented out the ref points in `index.js` got the modal shown without the above error:
https://github.com/cloudflare/react-modal2/blob/fb080b7e187bcc36b2918fba7021cf754a3e9c0a/index.js#L54
https://github.com/cloudflare/react-modal2/blob/fb080b7e187bcc36b2918fba7021cf754a3e9c0a/index.js#L81
https://github.com/cloudflare/react-modal2/blob/fb080b7e187bcc36b2918fba7021cf754a3e9c0a/index.js#L87

By inspecting the difference with `1.0.3`, the `ref` was already used. Any idea what could have made the difference?

I am using the `ReactGateway` wrapped around the modal, as it has been suggested in the `README.md`.

**Comment by thejameskyle** [comment]
Can you see if you are loading multiple copies of React (try running `npm dedupe`)? I can't reproduce this error.

**Comment by paazmaya** [comment]
Thanks for the hint, but it did not change anything.
However when installing the version `2.0.0`, it moves my `react` under its own `node_modules` and hence rest of the modules complain that it is missing.

Could it be because of making it a `dependency` here https://github.com/cloudflare/react-modal2/blob/master/package.json#L25?

For example https://github.com/rackt/react-router/blob/master/package.json#L70
has it in the `devDependencies`.

But then again, it was the same situation in `1.0.3`...

**Comment by thejameskyle** [comment]
Yeah I added the ref. But I'm not running into this issue at all. Can you create a test repo that reproduces this?

**Comment by paazmaya** [comment]
Ok, it seems that in case I had `react` installed previously and then install this module, `react` gets moved under it.
Running `npm dedupe` seems to move `react` back to the root of `node_modules`, hence fixing the issue.

Thank you for your patience.

**Comment by thejameskyle** [comment]
No worries. You may want to upgrade to npm v3 as it does a better job of dealing with this.
