### ISSUE TITLE
Modal in File

### ISSUE THREAD

**Issue by kennetpostigo** [cloudflare/react-modal2#9]
Hello,

I'm wondering if I have to declare a modal component every time I use this like you did in the redux example? or do I just import `react-modal2` like so 
```javascript
import Modal from 'react-modal2'
```

and declare a 
```jsx
<Modal> ... <Modal>
```

**Comment by thejameskyle** [comment]
From the README:

> Now this might seem like a lot to do every time you want to render a modal, but this is by design. You are meant to wrap ReactModal2 with your own component that you use everywhere. Your component can add it's own DOM, styles, animations, and behavior

So create your own modal component that you can easily import. Here is the reference example: https://github.com/cloudflare/cf-component-modal

**Comment by kennetpostigo** [comment]
@thejameskyle Thank you, Also one more little question. Does it work with functional components from `v.0.14`?

**Comment by thejameskyle** [comment]
There's no reason it wouldn't
